polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/presentation/', views.PresentationView.as_view(), name="presentation")
]

projectdummyapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text #Modifica el resultado de la consulta al modelo para que se vea como un objeto.
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question
from django.urls import reverse
from django.views import generic

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list,}
#     return render(request, 'polls/index.html', context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', { 'question': question })

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def  get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

class PresentationView(generic.DetailView): 
    model = Question
    template_name = 'polls/presentation.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk= question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'You did not select a choice'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/detail.css' %}" type="text/css">  
    <title>Document</title>
</head>
<body>
    <div class="container d-flex flex-column align-items-center justify-content-center ">
        <img src="https://i.ibb.co/bJ0ng71/icon-mi-megafono-removebg-preview.png" alt="logo">
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1> {{ question.question_text }} </h1>
            </legend>
            {% if error_message %}
                <p> <strong> {{ error_message }} </strong> </p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}" style="height:20px; width:20px;">
                <label for="choice{{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label> <br>
                {% endfor %}
        </fieldset>
        <input class="btn mt-4 " type="submit" value="Vote">
    </form>
</div>
</body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}" type="text/css">
    <title>Index Polls</title>
</head>
<body>
    <div class="container d-flex flex-column align-items-center justify-content-center ">
        <img src="https://i.ibb.co/bJ0ng71/icon-mi-megafono-removebg-preview.png" alt="logo">
        {% if latest_question_list %}
            <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No polls are available.</p>
        {% endif %}
    </div>
</body>
</html>

polls/templates/polls/presentation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/presentation.css' %}" type="text/css">
    <title>Document</title>
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="container-fluid d-flex flex-row justify-content-between">
                <a href="https://mimegafono.com/"> <img class="logo" src="https://i.ibb.co/bJ0ng71/icon-mi-megafono-removebg-preview.png" alt="icon-mi-megafono"> </a>          
              <img class="country" src="https://i.ibb.co/G3L3zpf/country-removebg-preview.png" alt="country">
              <div class="containerA d-flex dlex-row justify-content-center gap-3"> 
                <a href=""> BLOG </a>
                <a href=""> MEDIOS </a>
                <a href=""> CONTACTO </a>
            </div>
            <a class="text-decoration-none numberContact" href=""> +57 322 958 9638 </a>
            </div>
        </nav>
    </header>
    <main>
        <div class="containerImg">
            <h1 class="textWelcome">We democratize access to advertising in quality media.</h1>        
        </div>
        <div class="containerFigures d-flex flex-column align-items-center justify-content-center">
            <p class="text-center titleSteps"> Reach  <strong> more customers </strong> with these simple steps </p>
            <div class="figures d-flex flex-row justify-content-center gap-4 text-center">
                <div class="rectangle1">
                    <p class="textTarjet"> 1. Choose your target </p>
                </div>
                <div class="rectangle2">
                    <p class="textTarjet"> 2. Configure your ad </p>
                </div>
                <div class="rectangle3">
                    <p class="textTarjet"> 3. Pay insurance </p>
                </div>
            </div>
            <button class="btn my-4"> Start my ad </button>
        </div>
        <div class="containerPresentation py-4"> 
            <p class="text-center name mb-0"> Daniela Araujo Zapata </p>
            <p class="text-center"> Frontend Developer </p>
            <div class="presentation d-flex flex-row justify-content-center px-5">
                <div class="containerPhoto">
                    <img class="photo" src="https://i.ibb.co/ts6hgnF/1629813787228.jpg" alt="photoDaniela">
                </div>  
                <div class="description p-4 pb-2 text-center">
                    <p class="fs-2 fw-bold">  Why am I here? </p>
                    <p> I decided to start my training in the technology industry <br> for several reasons and during this process, <br> I have discovered more reasons to stay. </p>    
                    <ul class="fw-bolder">
                        <li> Challenger </li>
                        <li> Innovative </li>
                        <li> Changeable </li>
                        <li>  </li>
                    </ul>
                    <p> It is satisfying to create something with a team, <br> taking advantage of the great opportunity for <br> growth in this industry. </p>
                    <p class="fs-2 fw-bold">  What about me? </p>
                    <p> Well, there are many areas that are of interest to me.  </p>
                </div>          
            </div>
        </div>
        <div class="containerCards p-5 d-flex flex-row justify-content-center gap-4 mt-3">
            <div class="card" style="width: 18rem;">
                <img src="https://i.ibb.co/px28NHX/pexels-cottonbro-7437088-1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="text-center"> Technical area </h4>
                  <p class="card-text text-center">Improve my programming skills to become a versatile developer, able to bring great value to the team and to transmit his knowledge to others. I am interested in:
                   <ul class="interests ms-4">
                       <li> Web programming</li>
                       <li>Data science</li>    
                   </ul>
                </p>
                </div>
            </div>
            <div class="card" style="width: 18rem;">
                <img src="https://i.ibb.co/n8VWQf8/pexels-fauxels-3182804.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="text-center"> Work area </h4>
                  <p class="card-text text-center">Work team in which everyone contributes the best of themselves through the distributed tasks, exceeding the expectations of the proposed goals.</p>
                  <ul class="interests ms-4">
                    <li>Good work environment</li>
                    <li>Constant support from colleagues and leaders</li>    
                  </ul>   
                </div>
            </div>
            <div class="card" style="width: 18rem;">
                <img src="https://i.ibb.co/ncDLG66/pexels-mikhail-nilov-7682464.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="text-center"> Personal area </h4>
                  <p class="card-text text-center">Finding people who give me another perspective on situations, making the most of their opinions and skills.</p>
                  <ul class="interests ms-4">
                    <li>The experiencie</li>
                    <li>Social skills</li>    
                  </ul>   
                </div>
            </div>
        </div>
        <div class="containerInfo text-center m-4">
            <h1 class="my-5"> The best of me and my hobbies  </h1>
            <div class="d-flex flex-row justify-content-between flwx-wrap gap-5 mt-2">
                <div class="div_animate"> Lead </div>
                <div class="div_animate"> Commitment </div>
                <div class="div_animate"> Patience </div>
                <div class="div_animate"> Self-learning </div>
                <div class="div_animate"> Communication </div>
                <div class="div_animate"> Pro active </div>
            </div>
            <div class="d-flex flex-row justify-content-between flwx-wrap gap-5 ">
                <div class="div_animate"> Reading </div>
                <div class="div_animate"> Social life </div>
                <div class="div_animate"> Entertainment/Music </div>
                <div class="div_animate"> Travel </div>
            </div>
            </div>
        </div>
        
    </main>
    <footer> 
        <p class="textFooter"> &#169  Mi Megáfono Inc. 2022. All rights reserved. </p>
    </footer>
</body>
</html>

polls/templates/polls/results.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/results.css' %}" type="text/css">
    <title>Results Poll</title>
</head>
<body>
    <div class="container d-flex flex-column align-items-center justify-content-center">
        <img src="https://i.ibb.co/bJ0ng71/icon-mi-megafono-removebg-preview.png" alt="logo">
        <h1 class="mt-2"> {{ question.question_text }} </h1>
            <ul>
                {% for choice in question.choice_set.all %}
                    <li> {{ choice.choice_text }} - <strong> {{ choice.votes }} vote{{ choice.votes|pluralize }} </strong> </li>
                {% endfor %}
            </ul>
        <a class="mt-1" href="{% url 'polls:detail' question.id  %}"> Vote again? </a>
        <a href="{% url 'polls:presentation' question.id %}"> Go to presentation's view </a>
    </div>

</body>
</html>